### ISSUE TITLE
background-url images not loading from any source

### ISSUE THREAD

**Issue by rjbprime** [jsnee/vscode-dmbinder#30] opened 2021-06-15 12:15 UTC
Not sure if what's going on, but somewhere between release 0.5.9 and 0.5.12, rendering broke for loading images. Is this a regression of some sort? And can it be looked at? I've currently re-installed 0.5.9 via the method outlined in #16, via [your comment](https://github.com/jsnee/vscode-dmbinder/issues/16#issuecomment-644200972), and it seems to be working now.

I'm not a programmer by any means, so I mainly code with several examples on hand.

Kind regards

**Comment by jsnee** [comment] 2021-07-21 04:26
Duplicate of #29

**Closed by jsnee** 2021-07-21 04:26 UTC

**Comment by jsnee** [comment] 2021-07-23 15:43
@rjbprime Can you confirm this is fixed in the latest build of the extension? (0.5.13)

**Comment by rjbprime** [comment] 2021-11-30 05:14
Just tried loading images via raw.githack.com from a gitlab server. Fails to render them. But if I use the same code in Homebrewery proper, works fine. Would this be a permissions issue?

**Comment by jsnee** [comment] 2021-12-10 16:28
@rjbprime Not entirely sure, but it could be. Can you provide an example githack.com URL so I could diagnose? I used githack to load a github image and had no issues.
